import datetime

from dao.Option import Expiry

# Option trading constants
REFRESH_TIME_SECONDS = 30
TEST_RUN = False

MARGIN_DELAY_TIME = 10
MWPL_DELAY_TIME = 60
FUNDS_DELAY_TIME = 60
OPTION_STRATEGIES_DELAY_TIME = 25

CONTRACT_MIN_VALUE_TO_BE_SQ_OFFED = 2000

# OPTION Strategies constants
OPTIONS_STRATEGIES_EXPIRY_MONTH = Expiry.CURRENT
OPTIONS_STRATEGIES_TEST_RUN = False
OPTIONS_STRATEGIES_WRITE_TO_FILE = False
OPTIONS_STRATEGIES_WRITE_TO_DB = True
OPTIONS_STRATEGIES_STRIKE_RANGE = 8
OPTIONS_STRATEGIES_EXEL_FILE = output_file = '../data/output/' + datetime.datetime.now().strftime("%Y-%m-%d") + '.xlsx'

PROCESS_STARTED = 'Started'
PROCESS_COMPLETED = 'Completed'
PROCESS_FAILED = 'Failed'

#Brokers
ZERODHA_BROKER = 'ZERODHA'
ICICI_DIRECT_BROKER = 'ICICI'
NUVAMA_BROKER = 'NUVAMA'

#Order Status
ORDER_STATUS_OPEN = 'OPEN'
ORDER_STATUS_COMPLETE = 'COMPLETE'
ORDER_STATUS_CANCELLED = 'CANCELLED'
ORDER_STATUS_REJECTED = 'REJECTED'

